### ISSUE TITLE
Pin version of App Protect and Nginx

### ISSUE THREAD

**Issue by zbro-wtit422** [nginxinc/ansible-role-nginx-app-protect#119]
### Is your feature request related to a problem? Please describe
I would like the ability to pin the version of app protect and nginx plus so when this role is executed it installs the version specified instead of latest.

### Describe the solution you'd like
Variables for app protect and nginx plus package versions.

### Describe alternatives you've considered
Recommend approach to do this. For example, should you just make your own role to install nginx plus. Trying to use the official nginx ansible role.

**Comment by aknot242** [comment]
At one point this role had the limited ability to specify an App Protect version (other than the latest) but proved difficult to support due to the structure of the NGINX repository, the App Protect dependencies and the changes that had to be made to the repository URL if requesting a version of the package that was compiled against a previous version of NGINX Plus. This was further compounded by the differing logic that would be needed across all of the distros. For these reasons, we will not be adding it back due to the maintenance burden associated with maintaining all the logic across platforms.

If you are looking for a way to do this for a specific distro, you could create an installation playbook that follows dependency order logic similar to what is documented here (specifically step 9): https://docs.nginx.com/nginx-app-protect/admin-guide/install-for-controller/#debian-9

The version of the role that had limited support for this existed prior to [this commit](https://github.com/nginxinc/ansible-role-nginx-app-protect/commit/07a66c4f23ae935086a438054f84627393342b4b#diff-dcd8a9cdcaa79d0bf9015884b1fb2a7466e2456bf67c9ad2430271fd36f5187e) if you decide to build a playbook for this.
